# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob  
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.x'
          displayName: 'Install Node.js'

        - script: |
            cd albatross
            npm install
            npm run build
          displayName: 'npm install and build'
        - task: ArchiveFiles@2
          displayName: "Archive output"
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/albatross'
            includeRootFolder: false
            archiveFile: '$(Build.ArtifactStagingDirectory)/albatross.zip'
        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifact"
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/albatross.zip'
            ArtifactName: 'albatross'
        - task: Docker@2
          displayName: Build Docker image
          inputs:
            containerRegistry: 'albatrossimagesConnection'
            repository: '$(imageName)'
            command: 'buildAndPush'
            Dockerfile: './albatross/Dockerfile'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure subscription 1 (11983a98-f8fd-44f8-9458-06fc700f5941)'
            appType: 'webAppHyperVContainer'
            WebAppName: 'albatross1'
  - stage: Test
    displayName: Test Stage
    jobs:
      - job: TestJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              echo "test"
            displayName: 'npm install and build'
